# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-04 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe7\xbc\x96\xe5\x8f\xb7'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(choices=[(0, '\u5f85\u5ba1\u6279'), (1, '\u8fdb\u884c\u4e2d'), (2, '\u6682\u505c\u4e2d'), (3, '\u5df2\u7ed3\u9879'), (4, '\u5df2\u9a73\u56de')], default=0, verbose_name='\u9879\u76ee\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='projectapproval',
            name='result',
            field=models.IntegerField(choices=[(1, '\u5ba1\u6279\u901a\u8fc7'), (2, '\u5ba1\u6279\u9a73\u56de')], verbose_name='\u5ba1\u6279\u7ed3\u679c'),
        ),
    ]
