# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-04 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180904_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u9879\u76ee\u7f16\u53f7'),
        ),
    ]
