# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-12 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180904_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectattachment',
            name='name',
            field=models.FileField(upload_to=project.models.project_attachment_path, verbose_name='附件名'),
        ),
    ]
