# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-12 23:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filemanage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.FileField(upload_to=filemanage.models.save_file_path, verbose_name='文件名')),
                ('file_name', models.CharField(blank=True, max_length=100, verbose_name='文件名')),
                ('file_name_origin', models.CharField(blank=True, max_length=100, verbose_name='原始文件名')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('file_format', models.IntegerField(choices=[(1, '图片'), (2, '文档'), (3, '音乐'), (4, '视频'), (5, '压缩包'), (6, '数据文件'), (7, '可执行文件'), (8, '其他')], verbose_name='文件格式')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'ordering': ['-upload_time'],
            },
        ),
    ]
